/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#151a21',
        'on-primary-fixed-variant': '#006d4e',
        'outline-variant': '#44484f',
        background: '#0a0e14',
        'on-surface': '#f1f3fc',
        'inverse-surface': '#f8f9ff',
        'primary-fixed-dim': '#7defc0',
        'on-secondary': '#005d4d',
        'on-primary-fixed': '#004d36',
        'surface-variant': '#20262f',
        tertiary: '#78e3ff',
        'surface-container-low': '#0f141a',
        'error-dim': '#d7383b',
        'primary-fixed': '#8cfece',
        'secondary-fixed': '#54fcd8',
        error: '#ff716c',
        surface: '#0a0e14',
        'on-error-container': '#ffa8a3',
        'surface-bright': '#262c36',
        'primary-dim': '#7defc0',
        'on-primary-container': '#00291b',
        'secondary-dim': '#3fedca',
        'secondary-container': '#006b59',
        'on-secondary-container': '#defff3',
        'primary-container': '#3db489',
        'surface-container-lowest': '#000000',
        'on-error': '#490006',
        'on-surface-variant': '#a8abb3',
        'secondary-fixed-dim': '#3fedca',
        'surface-tint': '#8cfece',
        secondary: '#54fcd8',
        'on-primary': '#006146',
        'on-secondary-fixed': '#00483b',
        outline: '#72757d',
        'inverse-primary': '#006d4e',
        'surface-container-highest': '#20262f',
        'error-container': '#9f0519',
        'surface-container-high': '#1b2028',
        'inverse-on-surface': '#51555c',
        primary: '#8cfece',
        'on-background': '#f1f3fc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Syne', 'sans-serif'],
        body: ['Syne', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
        syne: ['Syne', 'sans-serif'],
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        'spin-reverse': 'spin 15s linear infinite reverse',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'skeleton': 'skeleton 1.5s ease-in-out infinite',
      },
      keyframes: {
        skeleton: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
      },
    },
  },
  plugins: [],
}
